CREATE DATABASE MillionRealEstateDB;
GO
USE MillionRealEstateDB;
GO

CREATE TABLE Owners (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Address NVARCHAR(300),
    Birthday DATETIME2 NULL,
    Photo NVARCHAR(500) NULL
);

CREATE TABLE Properties (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Address NVARCHAR(200) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    YearBuilt INT NOT NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    OwnerId INT NULL FOREIGN KEY REFERENCES Owners(Id)
);

CREATE TABLE PropertyImages (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PropertyId INT NOT NULL FOREIGN KEY REFERENCES Properties(Id),
    Url NVARCHAR(500) NOT NULL,
    IsPrimary BIT NOT NULL DEFAULT 0
);

CREATE TABLE PropertyTraces (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PropertyId INT NOT NULL FOREIGN KEY REFERENCES Properties(Id),
    DateSale DATETIME2 NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Value DECIMAL(18,2) NOT NULL,
    Tax DECIMAL(18,2) NOT NULL
);

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Role NVARCHAR(50) NOT NULL
);
